# problem 1

You are given the weights and values of `N` items, along with a knapsack of capacity `W`. Your task is to fill the knapsack to maximiuze the total value. You can break the items if necessary. Return a double value representing the maximum possible value that can be stored in the knapsack.

In [66]:
import numpy as np

In [77]:
#wt = np.array([20,24,36,40,42])
#val = np.array([12,35,41,25,32])
wt = np.array([20,24,36,40,42])
val = np.array([12,35,41,25,32])
#print(max(wt))

In [78]:
encode= val + wt/(10**2)
encode = np.sort(encode)
encode

array([12.2 , 25.4 , 32.42, 35.24, 41.36])

In [69]:
enc_wts = np.modf(encode)
print(enc_wts[0])
print(enc_wts[1])

[0.2  0.4  0.42 0.24 0.36]
[12. 25. 32. 35. 41.]


In [70]:
index = 0
residue = 0
fin = 0
for i in range(len(vsort)):
    fin += enc_wts[0][-i-1]
    index = i
    residue = fin - 1
    if fin > 1:
        break
print(f"index = {index}, residue = {residue}, fin = {fin}")

index = 2, residue = 0.020000000000003126, fin = 1.0200000000000031


In [71]:
enc_wts[1][index]  = (enc_wts[0][index] - residue)/enc_wts[0][index] * enc_wts[1][index]

In [72]:
index = 0
residue = 0
fin = 0
valsum = 0
for i in range(len(vsort)):
    fin += enc_wts[0][-i-1]
    index = i
    residue = fin - 1
    valsum += enc_wts[1][-i-1]
    if fin > 1:
        break

In [74]:
valsum

106.47619047619024