# Problem 2 - Date 7-8-2024

In [71]:
import numpy as np
import matplotlib.pyplot as plt

**Rules** :
* Each student gets at least one book
* Each book should be allocated to only 1 student
* Book allocation should be in **contiguous** manner.

Hence the condition should be that `len(arr) >= m` ALWAYS.

In [72]:
# input : siz -> number of books, stu -> number of students
stu = 12 #change input
siz = 25 #change input
bookpages = np.random.randint(0, 1000, siz)
print(list(bookpages))

[414, 595, 300, 114, 494, 536, 83, 633, 3, 349, 34, 750, 116, 566, 116, 942, 817, 590, 662, 189, 932, 976, 5, 532, 344]


### sort

In [73]:
# %load p3.py
#!/usr/bin/env python

# # Problem 3 - Date 7-8-2024

# In[1]:

"""
import numpy as np
import matplotlib.pyplot as plt


# In[24]:


n = 50
workarr = np.random.randint(0,1000,n)
print(len(workarr))
workarr
"""

# In[21]:


# Function to partition the array as per normal quicksort scheme
def partition_left(arr, low, high):
    pivot = arr[high]
    i = low
    for j in range(low, high):
        if arr[j] <= pivot:
            arr[i], arr[j] = arr[j], arr[i]
            i += 1
    arr[i], arr[high] = arr[high], arr[i]
    return i

# Function to perform random partition for randomized pivot selection
def partition_right(arr, low, high):
    r = np.random.randint(low, high) # random pivot not necessarily the last element of the array
    arr[r], arr[high] = arr[high], arr[r]
    return partition_left(arr, low, high)


# In[22]:


# Recursive function for quicksort that partitions the array after the pivot is set in the correct position
def quicksort(arr, low, high):
    if low < high:
        p = partition_right(arr, low, high)
        quicksort(arr, low, p - 1)
        quicksort(arr, p + 1, high)

In [74]:
quicksort(bookpages, 0, siz - 1)
print("Sorted array:")
bookpages

Sorted array:


array([  3,   5,  34,  83, 114, 116, 116, 189, 300, 344, 349, 414, 494,
       532, 536, 566, 590, 595, 633, 662, 750, 817, 932, 942, 976])

In [75]:
first= bookpages[:stu]
first

array([  3,   5,  34,  83, 114, 116, 116, 189, 300, 344, 349, 414])

The above list gives the first allocation

In [76]:
remain1 = bookpages[stu:]
remain1

array([494, 532, 536, 566, 590, 595, 633, 662, 750, 817, 932, 942, 976])

In [77]:
def min_allot(arr,remain,stu):
    stud = remain[:stu]
    sum_mat = sum(arr,stud)
    rem = arr[stu:]
    if len(arr) < 1:
        return sum_mat
    else:
        return min_allot(stud,rem,stu)

In [82]:
sum_mat = min(sum(sum1,remain2))
sum_mat

36854