# Problem 1 - Date 7-8-2024

## Short solution

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
rownum1, samenum, colnum2 = 2,3,4

matrix_1 = np.random.randint(0,1000, size= (rownum1,samenum))
matrix_2 = np.random.randint(0,1000, size= (samenum,colnum2))

print(matrix_1)
print("\n",matrix_2)

[[993 500 868]
 [613 614 609]]

 [[947  54 995 464]
 [751 841 944 867]
 [241  87 235 479]]


In [3]:
print("The product of the two matrices are")
print(matrix_1 @ matrix_2)

The product of the two matrices are
[[1525059  549638 1664015 1310024]
 [1188394  602459 1332666 1108481]]


## Step by step solving

In [4]:
def matmul(a1,a2):

    # algorithm - 
    # element wise multiplication. iterate starting with row wise method for first matrix and col wise for second matrix
    # a,b are elements in a1 row and a2 col respectively
    # first for loop iterates the elements in zip(a1 row, a2 col)
    # second for loop iterates the columns of second matrix
    # final for loop iterates rows of first matrix
    result = [[sum(a*b for a, b in zip(a1row, a2col)) for a2col in zip(*a2)] for a1row in a1]
    return result

In [5]:
print("result")
print(list(matmul(matrix_1,matrix_2)))

result
[[1525059, 549638, 1664015, 1310024], [1188394, 602459, 1332666, 1108481]]
